apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: datacube-ows-hpa
  namespace: open-datacube
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: datacube-ows
  minReplicas: 2
  maxReplicas: 20
  metrics:
    # CPU-based scaling
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

    # Memory-based scaling
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75

  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300 # Wait 5 min before scaling down
      policies:
        - type: Percent
          value: 25 # Scale down max 25% of pods at a time
          periodSeconds: 60
        - type: Pods
          value: 2 # Or max 2 pods at a time
          periodSeconds: 60
      selectPolicy: Min # Use the most conservative policy

    scaleUp:
      stabilizationWindowSeconds: 30 # Quick scale up
      policies:
        - type: Percent
          value: 100 # Can double pods quickly
          periodSeconds: 30
        - type: Pods
          value: 4 # Or add 4 pods at a time
          periodSeconds: 30
      selectPolicy: Max # Use the most aggressive policy
