apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-datacube

resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: datacube-ows
  app.kubernetes.io/component: web-service
