apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  - patch: |
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - key: "CriticalAddonsOnly"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          karpenter.sh/controller: "true"
    target:
      kind: Deployment
      labelSelector: "app.kubernetes.io/part-of=flux"
