extends: default

ignore: |
  /gotk-components.yaml
  /gotk-sync.yaml
  */flux-system/
  /**/gotk-*.yaml
  /**/*-gotk.yaml

rules:
  indentation:
    spaces: 2
  comments:
    min-spaces-from-content: 1
  line-length:
    max: 200
  document-start: disable
