apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: jupyterhub
spec:
  releaseName: jupyterhub
  targetNamespace: jupyterhub
  chart:
    spec:
      chart: jupyterhub
      version: "4.1.0"
      sourceRef:
        kind: HelmRepository
        name: jupyterhub
  interval: 5m0s
  values:
    # This is the default configuration for single user pods
    singleuser:
      # Use the piksel-core image from ECR
      image:
        name: "686410905891.dkr.ecr.ap-southeast-3.amazonaws.com/piksel-core"
        tag: "jupyter-7b35f73"
        pullPolicy: "Always"

      # Start with JupyterLab
      defaultUrl: "/lab"

      #  Run bash script define in singleuser.yaml
      lifecycleHooks:
        postStart:
          exec:
            command:
              - "bash"
              - "/etc/singleuser/k8s-lifecycle-hook-post-start.sh"

      # Resource allocation
      memory:
        limit: 4G
        guarantee: 1G
      cpu:
        limit: 2
        guarantee: 1

      # Persistent storage configuration
      storage:
        type: dynamic
        capacity: 10Gi
        homeMountPath: /home/jovyan
        dynamic:
          storageClass: gp2
          pvcNameTemplate: claim-{username}
          volumeNameTemplate: volume-{username}
          storageAccessModes:
            - ReadWriteOnce

        # Mount the custom Configmap as a volume
        extraVolumes:
          - name: lifecycle-hook-script
            configMap:
              name: user-etc-singleuser
              defaultMode: 0755
        extraVolumeMounts:
          - name: lifecycle-hook-script
            mountPath: /etc/singleuser
            readOnly: true

    # Proxy Configuration
    proxy:
      service:
        type: ClusterIP
      https:
        enabled: true
        type: offload # Let ingress handle SSL termination

    # Culling Configuration
    cull:
      enabled: true
      timeout: 3600 # 1 hour idle timeout
      every: 600 # Check every 10 minutes
