apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: jupyterhub
spec:
  releaseName: jupyterhub
  targetNamespace: jupyterhub
  chart:
    spec:
      chart: jupyterhub
      version: "4.1.0"
      sourceRef:
        kind: HelmRepository
        name: jupyterhub
  interval: 5m0s
  values:
    hub:
      config:
        DummyAuthenticator:
          password: test123
        JupyterHub:
          authenticator_class: dummy
    singleuser:
      memory:
        limit: 2G
        guarantee: 1G
      storage:
        type: none
    proxy:
      service:
        type: LoadBalancer
