apiVersion: v1
kind: ConfigMap
metadata:
  name: user-etc-singleuser
  namespace: jupyterhub
# This ConfigMap contains the post-start lifecycle hook script for JupyterHub single-user pods.
data:
  k8s-lifecycle-hook-post-start.sh: |
    #!/bin/bash
    set -e

    # --- Step 1 - Setup ---

    # Function for logging with timestamps
    log() {
      echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
    }

    log "Running post-start hook"

    # Configuration variables
    GITHUB_REPO="${GITHUB_REPO:-https://github.com/piksel-ina/piksel-notebooks.git}"
    BRANCH="${BRANCH:-main}"
    TARGET_DIR="${TARGET_DIR:-/home/jovyan/examples}"
    CONDA_ENV="${CONDA_ENV:-notebook}"

    # Create necessary directories

    log "Initializing directories"
    mkdir -p ~/.jupyter/lab/user-settings/@jupyterlab/docmanager-extension/
    mkdir -p ~/.jupyter/lab/user-settings/@jupyterlab/apputils-extension/


    # --- Step 2 - Sync Notebooks --- 

    # Sync with gitpuller
    log "Syncing notebook examples from ${GITHUB_REPO}"
    if /srv/conda/envs/${CONDA_ENV}/bin/gitpuller "${GITHUB_REPO}" "${BRANCH}" "${TARGET_DIR}"; then
      log "Successfully synced clean examples to ${TARGET_DIR}"
    else
      log "Warning: Failed to sync examples repository"
    fi


    # --- Step 3 - Update JupyterLab settings ---

    log "Updating JupyterLab settings"

    # Markdown preview and autosave settings
    cat <<EOF > ~/.jupyter/lab/user-settings/@jupyterlab/docmanager-extension/plugin.jupyterlab-settings
    {
    "defaultViewers": {
        "markdown": "Markdown Preview"
    },
    "autosave": true,
    "autosaveInterval": 120
    }
    EOF
    log "Set markdown preview and autosave settings"    

    # Disable news notifications
    cat <<EOF > ~/.jupyter/lab/user-settings/@jupyterlab/apputils-extension/notification.jupyterlab-settings
    {
      "fetchNews": "false"
    }
    EOF
    log "Disabled JupyterLab news notifications"

    echo "Removing lost+found"
    # Remove empty lost+found directories
    rmdir ~/lost+found/ || true

    log "Post-start hook completed"
