apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-workflows
resources:
  - ../../base/argo
patches:
  - path: argo-patch.yaml
    target:
      kind: HelmRelease
      name: argo-workflows
      namespace: argo-workflows
