apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: datacube-explorer
  namespace: open-datacube
spec:
  values:
    # Ingress configuration
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        external-dns.alpha.kubernetes.io/hostname: grafana.dev.pik-sel.id
      hosts:
        - host: explorer.pik-sel.id
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: explorer-ingress
          hosts:
            - explorer.domain.com
