apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: open-datacube
resources:
  - ../../base/odc
  - explorer-ingress.yaml
# patches:
#   - path: explorer-patch.yaml
#     target:
#       kind: HelmRelease
#       name: datacube-explorer
#       namespace: open-datacube
