apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../../base/odc

patches:
  - path: explorer-patch.yaml
    target:
      kind: HelmRelease
      name: datacube-explorer
      namespace: open-datacube
