apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: odc-metadata-update
  namespace: argo-workflows
spec:
  serviceAccountName: argo-workflows-executor
  entrypoint: metadata-update
  podGC:
    strategy: OnPodCompletion
  podMetadata:
    annotations:
      karpenter.sh/do-not-disrupt: "true"
    labels:
      app: odc-metadata-update
  ttlStrategy:
    secondsAfterCompletion: 300
  templates:
    - name: metadata-update
      container:
        name: odc
        image: 686410905891.dkr.ecr.ap-southeast-3.amazonaws.com/inadc-core:v20260429-1009
        command: [bash, -c]
        args:
          - |
            datacube --version
            datacube metadata update --allow-unsafe https://raw.githubusercontent.com/piksel-ina/piksel-core/main/metadata/custom_metadata.odc-type.yaml
        env:
          - name: ODC_DEFAULT_DB_HOSTNAME
            value: "pg-proxy-service.database.svc.cluster.local"
          - name: ODC_DEFAULT_DB_PORT
            value: "6432"
          - name: ODC_DEFAULT_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: odc
                key: username
          - name: ODC_DEFAULT_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: odc
                key: password
          - name: ODC_DEFAULT_DB_DATABASE
            value: "odc"
          - name: ODC_DEFAULT_INDEX_DRIVER
            value: "postgis"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
