apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../../base/monitoring/kube-prometheus-stack
  - ../../base/monitoring/loki-stack
  - ../../base/monitoring/monitoring-config
patches:
  - path: kube-prometheus-stack-values.yaml
    target:
      kind: HelmRelease
      name: kube-prometheus-stack
      namespace: monitoring
  - path: loki-patch.yaml
    target:
      kind: HelmRelease
      name: loki
      namespace: monitoring
configurations:
  - ../../base/monitoring/kube-prometheus-stack/kustomizeconfig.yaml
