apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  values:
    # Development-specific overrides
    singleBinary:
      persistence:
        size: 5Gi # Smaller storage for dev
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi

    minio:
      persistence:
        size: 3Gi # Smaller storage for dev
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi

    loki:
      limits_config:
        retention_period: 12h # Shorter retention for dev
