apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../../base/monitoring/kube-prometheus-stack
  # - ../../base/monitoring/loki-stack
  - ./dashboards
patches:
  - path: kube-prometheus-stack-values.yaml
    target:
      kind: HelmRelease
      name: kube-prometheus-stack
      namespace: monitoring
