apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aws-efs-csi-driver
  namespace: filesystem
spec:
  interval: 10m
  chart:
    spec:
      chart: aws-efs-csi-driver
      version: "3.1.9"
      sourceRef:
        kind: HelmRepository
        name: aws-efs-csi-driver
        namespace: filesystem
      interval: 5m
  values:
    controller:
      serviceAccount:
        create: true
        name: efs-csi-controller-sa
        annotations:
          eks.amazonaws.com/role-arn: ${IRSA_ROLE_ARN}
      resources:
        limits:
          cpu: "100m"
          memory: "128Mi"
        requests:
          cpu: "10m"
          memory: "40Mi"
    node:
      resources:
        limits:
          cpu: "100m"
          memory: "128Mi"
        requests:
          cpu: "10m"
          memory: "40Mi"
    nodeSelector:
      kubernetes.io/os: linux
    tolerations:
      - operator: Exists
