apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- repository.yaml
- helmrelease.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: aws-efs-csi-driver
