apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: aws-efs-csi-driver
  namespace: filesystem
spec:
  interval: 1h
  url: https://kubernetes-sigs.github.io/aws-efs-csi-driver
