apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: jupyterhub
spec:
  values:
    hub:
      db:
        type: postgres
        upgrade: true
  valuesFrom:
    - kind: Secret
      name: hub-db-secret
      valuesKey: db_url
      targetPath: hub.db.url
      optional: false
