apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: jupyterhub
spec:
  values:
    hub:
      db:
        type: postgres
        upgrade: true
        url: postgresql://jupyterhub@pg-proxy-service.database.svc.cluster.local:6432/jupyterhub
        password: "${JUPYTERHUB_DB_PASSWORD}"
  valuesFrom:
    - kind: Secret
      name: hub-db-secret
      valuesKey: password
      targetPath: hub.db.password
    - kind: Secret
      name: jupyterhub
      valuesKey: values.yaml
      optional: false
