apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jupyterhub
resources:
  - ../../base/jupyterhub
patches:
  - path: hub-patch.yaml
    target:
      kind: HelmRelease
      name: jupyterhub
      namespace: jupyterhub
  - path: ingress.yaml
    target:
      kind: HelmRelease
      name: jupyterhub
      namespace: jupyterhub
