apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: jupyterhub
spec:
  values:
    hub:
      db:
        url: postgresql://jupyterhub@pg-proxy-service.database.svc.cluster.local:6432/jupyterhub
      config:
        GenericOAuthenticator:
          oauth_callback_url: "https://sandbox.staging.pik-sel.id/hub/oauth_callback"
          logout_redirect_url: "https://sandbox.dev.pik-sel.id/hub/home"
  valuesFrom:
    - kind: Secret
      name: jupyterhub
      valuesKey: values.yaml
      optional: false
