apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: jupyterhub
spec:
  values:
    singleuser:
      extraFiles:
        jupyter_server_deployment_config.py:
          mountPath: /home/jovyan/.jupyter/jupyter_server_deployment_config.py
          stringData: |
            # This file gets executed AFTER the main config
            import os
            c = get_config()

            # ---- environment-specific network settings ---------------
            c.ServerApp.allow_origin = 'https://sandbox.staging.pik-sel.id' 
            c.ServerApp.allow_credentials = True
            c.ServerApp.allow_remote_access = True
            c.ServerApp.trust_xheaders = True
            c.ServerApp.disable_check_xsrf = True 
            c.ServerApp.allow_unauthenticated_access = True

            # ---- environment-specific timeouts -----------------------
            c.ServerApp.shutdown_no_activity_timeout = 1800 

            # ---- environment-specific security -----------------------
            c.ServerApp.cookie_options = {
                'secure': True,
                'httponly': True,
                'samesite': 'Lax'
            }

            # ---- Kernel management settings --------------------------
            c.MappingKernelManager.kernel_info_timeout = 300
