apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- sc-coastline-changes.yaml
- sc-public-data.yaml


labels:
- includeSelectors: true
  pairs:
    environment: development
patches:
- path: values.yaml
