apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-coastline-changes
provisioner: efs.csi.aws.com
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  provisioningMode: efs-ap-static
  fileSystemId: fs-087c5ed794f5c6cd9
  accessPointId: fsap-01ab873361c534e91
---
# Create a PersistentVolumeClaim for Coastline Changes Projects in EFS
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-coastline-data
  namespace: jupyterhub
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-coastline-changes
  resources:
    requests:
      storage: 500Mi
