apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-coastline-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-coastline-changes
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-087c5ed794f5c6cd9::fsap-01ab873361c534e91
    volumeAttributes:
      path: "/coastline-changes"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-coastline-changes
provisioner: efs.csi.aws.com
volumeBindingMode: Immediate
allowVolumeExpansion: true
---
# Create a PersistentVolumeClaim for Coastline Changes Projects in EFS
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-coastline-data
  namespace: jupyterhub
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-coastline-changes
  resources:
    requests:
      storage: 2Gi
