apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-public-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-public-data
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-087c5ed794f5c6cd9::fsap-0949bf9a21008aba1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-public-data
provisioner: efs.csi.aws.com
volumeBindingMode: Immediate
allowVolumeExpansion: true
---
# Create a PersistentVolumeClaim for JupyterLab to use the EFS
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-public-data
  namespace: jupyterhub
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-public-data
  resources:
    requests:
      storage: 500Mi
