apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-alloy
spec:
  interval: 15m
  chart:
    spec:
      chart: alloy
      version: "1.1.1" # App version: 1.9.1
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # This section configures Alloy to run as a DaemonSet
    # to collect logs from every node in the cluster.
    controller:
      type: "daemonset"
      # Tolerations to ensure the agent runs on all nodes
      daemonset:
        tolerations:
          - effect: NoSchedule
            operator: Exists
          - key: "CriticalAddonsOnly"
            operator: "Exists"

    # This is the configuration file for Alloy, written in the "River" language.
    # It defines where to get logs from and where to send them.
    # See: https://grafana.com/docs/alloy/latest/configure/kubernetes/
    configMap:
      create: true
      content: |
        // Discover Kubernetes pods and scrape their container logs.
        loki.source.kubernetes "pods" {
          forward_to = [loki.write.default.receiver]
        }

        // Define the Loki server to send logs to.
        loki.write "default" {
          endpoint {
            // This is the address of your Loki service from the other HelmRelease.
            // Format: http://<service-name>.<namespace>.svc.cluster.local:<port>/loki/api/v1/push
            url = "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
          }
        }
