apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
spec:
  interval: 5m
  timeout: 1m
  dependsOn:
    - name: kube-prometheus-stack
  chart:
    spec:
      # Pin chart version to match Loki for compatibility.
      version: "6.0.0"
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
      interval: 60m
  values:
    config:
      clients:
        - url: http://loki-gateway/loki/api/v1/push
          tenant_id: 1
