apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-workflows
spec:
  values:
    useStaticCredentials: false
    server:
      logging:
        level: debug
        globallevel: "9"
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/hostname: argo.dev.pik-sel.id
        hosts:
          - argo.dev.pik-sel.id
        tls:
          - hosts:
              - argo.dev.pik-sel.id
            secretName: argo-ingress
        level: debug
      authModes: [sso]
      sso:
        secure: true
        enabled: true
        issuer: "https://cognito-idp.ap-southeast-3.amazonaws.com/ap-southeast-3_ZFzkRhjdu"
        sessionExpiry: 240h
        clientId:
          name: argo-client-secret
          key: client-id
        clientSecret:
          name: argo-client-secret
          key: client-secret
        scopes:
          - openid
          - email
          - profile
        redirectUrl: https://argo.dev.pik-sel.id/oauth2/callback
        customGroupClaimName: "cognito:groups"
        # userInfoPath: "/oauth2/userInfo"
        rbac:
          enabled: true

    artifactRepository:
      archiveLogs: true
      s3:
        bucket: "piksel-dev-argo-artifacts-dep"
        region: ap-southeast-3
        endpoint: s3.ap-southeast-3.amazonaws.com
        keyFormat: "artifacts/{{workflow.namespace}}/{{workflow.name}}/{{pod.name}}"
        useSDKCreds: true

    workflow:
      serviceAccount:
        create: true
        name: "argo-workflows-executor"
        annotations:
          workflows.argoproj.io/rbac-rule: "true"
          workflows.argoproj.io/rbac-rule-precedence: "1"
          eks.amazonaws.com/role-arn: "arn:aws:iam::236122835646:role/iam-role-for-argo-workflow-service-account"
      rbac:
        create: true

    controller:
      persistence:
        postgresql:
          host: pg-proxy-service.database.svc.cluster.local
          port: 6432
          database: argo
          tableName: workflows
          userNameSecret:
            name: argo
            key: username
          passwordSecret:
            name: argo
            key: password
          ssl: false
