# Sentinel-2 L2A Workflow
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: s1-rtc-bulk-index-
  namespace: argo-workflows
spec:
  serviceAccountName: argo-workflows-executor
  workflowTemplateRef:
    name: datacube-bulk-indexer
  arguments:
    parameters:
      - name: catalog
        value: "https://planetarycomputer.microsoft.com/api/stac/v1/"
      - name: collections
        value: "sentinel-1-rtc"
      - name: datetime
        value: "2014-9-9/2025-09-11"
      - name: arguments
        value: "--rename-product=s1_rtc"
      - name: time-chunks
        value: "6"
      - name: min-lon
        value: "95"
      - name: max-lon
        value: "141"
      - name: max-lat
        value: "6"
      - name: min-lat
        value: "-11"
      - name: cell-size
        value: "5"
