# --- Applications Kustomization for the development cluster ---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  # How often Flux checks for changes (every 1 minute)
  interval: 1m0s
  dependsOn:
    # Ensure infra-configs is applied before apps
    - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  # Path to the kustomization files for development apps
  path: ./apps/development
  # Remove resources that are no longer defined in the source
  prune: true
  # Wait for the resources to be ready before marking the kustomization as ready
  wait: true
  timeout: 5m0s
