---
# --- Infrastructure controllers for the development cluster ---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  # Ensure jobs are applied before controllers
  dependsOn:
    - name: infra-jobs
  # How often Flux checks for changes (every 1 hour)
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  # Path to the kustomization files for infrastructure controllers
  path: ./infrastructure/controllers
  prune: true
  wait: true
---
# --- Infrastructure configurations for the development cluster ---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  # Ensure infra-controllers is applied before infra-configs
  dependsOn:
    - name: infra-controllers
  # How often Flux checks for changes (every 1 hour)
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  # Path to the kustomization files for infrastructure configurations
  path: ./infrastructure/configs
  prune: true
  wait: true
---
# --- EFS CSI ---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-efs-csi
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/efs-csi/development
  prune: true
  wait: true
