---
# --- Notification configuration for FluxCD ---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: notifier
  namespace: flux-system
spec:
  summary: "Development notifications"

  # Use the Slack provider for notifications
  providerRef:
    name: slack-dev

  # Severity set to info for development environment
  # This will send notifications for all events
  eventSeverity: info

  # Define the event sources that will trigger notifications
  eventSources:
    - kind: GitRepository
      name: "*"
    - kind: Kustomization
      name: "*"
