apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-efs-public-data-argo
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-01ee336c8673d11e9::fsap-0126d051fe0f291c3

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-public-data
  namespace: argo-workflows
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: pv-efs-public-data-argo
  resources:
    requests:
      storage: 1Gi
