apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-data
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: "fs-01ee336c8673d11e9"
  directoryPerms: "770"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
  basePath: "/data"
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - tls
