apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stac
resources:
  - ../../base/stac
  - ingress.yaml
patches:
  - path: stac-fastapi-db-password.yaml
    target:
      kind: Deployment
      name: stac-fastapi
      namespace: stac
  - path: stac-fastapi-ingress.yaml
    target:
      kind: Ingress
      name: stac-ingress
      namespace: stac
  - path: stac-browser-deployment.yaml
    target:
      kind: Deployment
      name: stac-browser
      namespace: stac
