{
 "title": "RAM and CPU Utilization",
 "description": "Shows RAM and CPU utilization grouped by namespaces, deployments and specific pods. This dashboard shows the values at specific point in time, its useful for getting an instant feeling about what takes most of the resources in the cluster.",
 "tags": [
  "RAM",
  "CPU",
  "NODES"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "gauge",
   "description": "The memory usage in percentage of all nodes in the cluster.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (node_memory_MemTotal_bytes) - sum (node_memory_MemAvailable_bytes)) / sum (node_memory_MemTotal_bytes) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "The average CPU usage of all the nodes in the cluster.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100 - (avg by (node) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Nodes",
   "type": "table",
   "description": "A list of all nodes in the cluster along with their spec. This table helps to get a quick idea about the resources in the cluster.",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 0 },
   "targets": [
    { "expr": "node_uname_info", "legendFormat": "__auto" },
    {
     "expr": "count by(node) (node_cpu_seconds_total)",
     "legendFormat": "CPUs"
    },
    {
     "expr": "sum by (node) (node_memory_MemTotal_bytes)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Memory usage by namespace",
   "type": "bargauge",
   "description": "The memory usage in a cluster grouped by Kubernetes namespace",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (namespace) (container_memory_working_set_bytes{pod!=\"\",container!=\"POD\", container!=\"\"}))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory usage by deployment",
   "type": "bargauge",
   "description": "The memory usage in a cluster grouped by Kubernetes deployment",
   "gridPos": { "h": 13, "w": 9, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (container, namespace) (container_memory_working_set_bytes{container!=\"POD\", container!=\"\"}))",
     "legendFormat": "{{ namespace }} - {{ container}}"
    }
   ]
  },
  {
   "title": "Memory usage by pod",
   "type": "bargauge",
   "description": "The memory usage in a cluster grouped by Kubernetes pod",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (pod, namespace) (container_memory_working_set_bytes{pod!=\"\",container!=\"POD\", container!=\"\"}))",
     "legendFormat": "{{ namespace }} - {{ pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage by namespace",
   "type": "bargauge",
   "description": "The CPU usage in a cluster grouped by Kubernetes namespace",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (namespace) (rate(container_cpu_usage_seconds_total{container!=\"\", container!=\"POD\"}[5m])))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU Usage by deployment",
   "type": "bargauge",
   "description": "The CPU usage in a cluster grouped by Kubernetes deployment",
   "gridPos": { "h": 13, "w": 9, "x": 7, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (container, namespace) (rate(container_cpu_usage_seconds_total{container!=\"\", container!=\"POD\"}[5m])))",
     "legendFormat": "{{ namespace }} - {{container}}"
    }
   ]
  },
  {
   "title": "CPU Usage by pod",
   "type": "bargauge",
   "description": "The CPU usage in a cluster grouped by Kubernetes pod",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (pod, namespace) (rate(container_cpu_usage_seconds_total{container!=\"\", container!=\"POD\"}[5m])))",
     "legendFormat": "{{ namespace }} - {{ pod}}"
    }
   ]
  }
 ]
}