apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbouncer-config
  namespace: database
data:
  pgbouncer.ini: |
    [databases]
    * = host=db-endpoint.database.svc.cluster.local port=5432 sslmode=verify-ca sslcert=/etc/pgbouncer/certs/rds-ca.pem

    [pgbouncer]
    pool_mode = transaction
    max_client_conn = 200
    default_pool_size = 20
    reserve_pool_size = 5
    auth_type = plain
    auth_file = /etc/pgbouncer/userlist.txt
    listen_addr = *
    listen_port = 5432
    logfile = /var/log/pgbouncer/pgbouncer.log
    pidfile = /tmp/pgbouncer.pid
    sslcert = /etc/pgbouncer/certs/rds-ca.pem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-proxy
  namespace: database
  labels:
    app: pg-proxy
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: pg-proxy
  template:
    metadata:
      labels:
        app: pg-proxy
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: pg-proxy
                topologyKey: "kubernetes.io/hostname"
      initContainers:
        - name: aggregate-secrets-and-ca
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              # Create certs directory
              mkdir -p /shared-auth/certs

              # Download RDS CA bundle for ap-southeast-3 region
              echo "Downloading RDS CA bundle for ap-southeast-3..."
              wget -O /shared-auth/certs/rds-ca.pem https://truststore.pki.rds.amazonaws.com/ap-southeast-3/ap-southeast-3-bundle.pem
              if [ $? -eq 0 ]; then
                echo "RDS CA bundle downloaded successfully."
              else
                echo "Error: Failed to download RDS CA bundle." >&2
                exit 1
              fi

              # Create userlist.txt by reading mounted secrets
              echo "Generating userlist.txt from Secrets..."
              echo "" > /shared-auth/userlist.txt
              # List of secrets (users) matching your provided list
              for secret in argo jupyterhub grafana stac stacread odc odcread; do
                if [ -f "/secrets/${secret}/password" ]; then
                  password=$(cat "/secrets/${secret}/password")
                  echo "\"${secret}\" \"${password}\"" >> /shared-auth/userlist.txt
                else
                  echo "Warning: Secret for ${secret} not found or missing password key" >&2
                fi
              done
              echo "Userlist.txt generated successfully."

              # Copy the pgbouncer config file
              cp /config/pgbouncer.ini /shared-auth/pgbouncer.ini
              echo "pgbouncer.ini copied successfully."
          volumeMounts:
            - name: shared-auth
              mountPath: /shared-auth
            - name: pgbouncer-config
              mountPath: /config
              readOnly: true
            - name: argo-secret
              mountPath: /secrets/argo
              readOnly: true
            - name: jupyterhub-secret
              mountPath: /secrets/jupyterhub
              readOnly: true
            - name: grafana-secret
              mountPath: /secrets/grafana
              readOnly: true
            - name: stac-secret
              mountPath: /secrets/stac
              readOnly: true
            - name: stacread-secret
              mountPath: /secrets/stacread
              readOnly: true
            - name: odc-secret
              mountPath: /secrets/odc
              readOnly: true
            - name: odcread-secret
              mountPath: /secrets/odcread
              readOnly: true

      containers:
        - name: pg-proxy
          image: bitnami/pgbouncer:1.24.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            # Bitnami PgBouncer specific environment variables
            - name: POSTGRESQL_HOST
              value: "db-endpoint.database.svc.cluster.local"
            - name: POSTGRESQL_PORT
              value: "5432"
            - name: POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: password
            - name: PGBOUNCER_CONFIG_FILE
              value: /etc/pgbouncer/pgbouncer.ini
            - name: PGBOUNCER_AUTH_TYPE
              value: "plain"
            - name: PGBOUNCER_AUTH_FILE
              value: "/etc/pgbouncer/userlist.txt"
            - name: PGBOUNCER_POOL_MODE
              value: "transaction"
            - name: PGBOUNCER_MAX_CLIENT_CONN
              value: "200"
            - name: PGBOUNCER_DEFAULT_POOL_SIZE
              value: "20"
            - name: PGBOUNCER_RESERVE_POOL_SIZE
              value: "5"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: shared-auth
              mountPath: /etc/pgbouncer
              readOnly: true
            - name: log-dir
              mountPath: /var/log/pgbouncer
      volumes:
        - name: shared-auth
          emptyDir: {}
        - name: argo-secret
          secret:
            secretName: argo
        - name: jupyterhub-secret
          secret:
            secretName: jupyterhub
        - name: grafana-secret
          secret:
            secretName: grafana
        - name: stac-secret
          secret:
            secretName: stac
        - name: stacread-secret
          secret:
            secretName: stacread
        - name: odc-secret
          secret:
            secretName: odc
        - name: odcread-secret
          secret:
            secretName: odcread
        - name: pgbouncer-config
          configMap:
            name: pgbouncer-config
        - name: log-dir
          emptyDir: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: pg-proxy-service
  namespace: database
  labels:
    app: pg-proxy
spec:
  selector:
    app: pg-proxy
  ports:
    - name: pgbouncer
      protocol: TCP
      port: 5432 # External port (what clients will connect to)
      targetPort: 6432 # Internal port (what PgBouncer is listening on)
  type: ClusterIP
