apiVersion: v1
kind: Service
namespace: open-datacube
metadata:
  name: explorer-svc
  labels:
    app: explorer-svc
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: explorer
