---
# Notitication Providers for FluxCD notifications in Dev Environment
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: slack-dev
  namespace: flux-system
spec:
  type: slack
  # The channel to send notifications to (must be created in Slack)
  channel: flux-piksel-dev-env
  # The secret is called slack-webhook and the key is url
  secretRef:
    name: slack-webhook-dev
---
# Notification Providers for FluxCD notifications in Prod Environment
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: slack-prod
  namespace: flux-system
spec:
  type: slack
  # The channel to send notifications to (must be created in Slack)
  channel: flux-piksel-prod-env
  # The secret is called slack-webhook and the key is url
  secretRef:
    name: slack-webhook-prod
---

