apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: datacube-stac-indexer
  namespace: argo-workflows
spec:
  serviceAccountName: argo-workflows-executor
  entrypoint: stac-indexing
  podGC:
    strategy: OnWorkflowCompletion
  ttlStrategy:
    secondsAfterCompletion: 300
  arguments:
    parameters:
      - name: catalog
        value: "https://stac.staging.example.com"
      - name: arguments
        value: "--rename-product=s2_l2a"
      - name: bbox
        value: "-180.0,-70,180.0,70"
      - name: datetime
        value: "2020-04-01/2020-09-30"
      - name: collections
        value: "example-collection"
  templates:
    - name: stac-indexing
      inputs:
        parameters:
          - name: catalog
            value: "{{workflow.parameters.catalog}}"
          - name: collections
            value: "{{workflow.parameters.collections}}"
          - name: bbox
            value: "{{workflow.parameters.bbox}}"
          - name: datetime
            value: "{{workflow.parameters.datetime}}"
          - name: arguments
            value: "{{workflow.parameters.arguments}}"
      container:
        name: odc-container
        image: 686410905891.dkr.ecr.ap-southeast-3.amazonaws.com/piksel-core:odc-v0.2.0
        command:
          - bash
        args:
          - "-c"
          - |
            echo "🌍 Processing STAC indexing"
            echo "📍 Bbox: {{inputs.parameters.bbox}}"
            echo "🗓️ Datetime: {{inputs.parameters.datetime}}"

            stac-to-dc \
            --catalog-href={{inputs.parameters.catalog}} \
            --collections={{inputs.parameters.collections}} \
            --bbox={{inputs.parameters.bbox}} \
            --datetime={{inputs.parameters.datetime}} \
            {{inputs.parameters.arguments}}

            echo "✅ Completed STAC indexing"

        env:
          - name: ODC_DEFAULT_DB_HOSTNAME
            value: "pg-proxy-service.database.svc.cluster.local"
          - name: ODC_DEFAULT_DB_PORT
            value: "6432"
          - name: ODC_DEFAULT_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: odc
                key: username
          - name: ODC_DEFAULT_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: odc
                key: password
          - name: ODC_DEFAULT_DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: odc
                key: username
          - name: ODC_DEFAULT_INDEX_DRIVER
            value: "postgis"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2"
