apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: datacube-delete-product
  namespace: argo-workflows
spec:
  serviceAccountName: argo-workflows-executor
  entrypoint: datacube-delete-product
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
  podMetadata:
    annotations:
      karpenter.sh/do-not-disrupt: "true"
    labels:
      app: datacube-delete-product
  arguments:
    parameters:
      - name: product
        value: example_product
  templates:
    - name: datacube-delete-product
      serviceAccountName: argo-workflows-executor
      metadata:
        labels:
          app: argo-delete-product
      inputs:
        parameters:
          - name: product
            value: "{{workflow.parameters.product}}"
      container:
        name: odc-container
        image: 686410905891.dkr.ecr.ap-southeast-3.amazonaws.com/piksel-core:odc-v0.2.0
        command: ["bash", "-c"]
        args:
          - |
            set -e
            echo "Starting product deletion for: {{ inputs.parameters.product }}"

            # Check if product exists first
            if datacube product list | grep -q "{{ inputs.parameters.product }}"; then
              echo "Product {{ inputs.parameters.product }} found. Proceeding with deletion..."
              datacube product delete --force "{{ inputs.parameters.product }}"
            else
              echo "Product {{ inputs.parameters.product }} not found in datacube"
              exit 1
            fi
        env:
          - name: PRODUCT_NAME
            value: "{{inputs.parameters.product}}"
          - name: ODC_DEFAULT_DB_HOSTNAME
            value: "pg-proxy-service.database.svc.cluster.local"
          - name: ODC_DEFAULT_DB_PORT
            value: "6432"
          - name: ODC_DEFAULT_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: odc
                key: username
          - name: ODC_DEFAULT_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: odc
                key: password
          - name: ODC_DEFAULT_DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: odc
                key: username
          - name: ODC_DEFAULT_INDEX_DRIVER
            value: "postgis"
