apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: datacube-product-sync
  namespace: argo-workflows
spec:
  serviceAccountName: argo-workflows-executor
  entrypoint: product-sync
  podGC:
    strategy: OnPodCompletion
  podMetadata:
    annotations:
      karpenter.sh/do-not-disrupt: "true"
    labels:
      app: datacube-product-sync
  ttlStrategy:
    secondsAfterCompletion: 300
  templates:
    - name: product-sync
      serviceAccountName: argo-workflows-executor
      inputs:
        parameters:
          - name: product-list
            value: "https://raw.githubusercontent.com/piksel-ina/piksel-core/main/products.csv"
      container:
        name: odc-container
        image: 686410905891.dkr.ecr.ap-southeast-3.amazonaws.com/piksel-core:odc-v0.2.0
        command:
          - bash
        args:
          - "-c"
          - |
            datacube --version
            dc-sync-products {{inputs.parameters.product-list}} --update-if-exists
            datacube product list
        env:
          - name: ODC_DEFAULT_DB_HOSTNAME
            value: "pg-proxy-service.database.svc.cluster.local"
          - name: ODC_DEFAULT_DB_PORT
            value: "6432"
          - name: ODC_DEFAULT_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: odc
                key: username
          - name: ODC_DEFAULT_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: odc
                key: password
          - name: ODC_DEFAULT_DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: odc
                key: username
          - name: ODC_DEFAULT_INDEX_DRIVER
            value: "postgis"
