apiVersion: v1
kind: Service
metadata:
  name: pg-proxy-service
  namespace: database
  labels:
    app: pg-proxy
spec:
  selector:
    app: pg-proxy
  ports:
    - name: pgbouncer
      protocol: TCP
      port: 6432
      targetPort: 6432
  type: ClusterIP
