apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: datacube-explorer
  namespace: open-datacube
spec:
  interval: 10m
  chart:
    spec:
      chart: datacube-explorer
      version: "0.5.31"
      sourceRef:
        kind: HelmRepository
        name: datacube-charts
        namespace: flux-system
      interval: 5m
  values:
    # Application configuration
    image:
      repository: opendatacube/explorer
      tag: "latest"
      pullPolicy: IfNotPresent

    # Service configuration
    service:
      type: ClusterIP
      port: 8080

    # Ingress configuration
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
      hosts:
        - host: explorer.domain.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: datacube-explorer-tls
          hosts:
            - explorer.domain.com

    # Environment variables for datacube-explorer
    env:
      - name: DB_HOSTNAME
        value: "pg-proxy-service.database.svc.cluster.local"
      - name: DB_PORT
        value: "6432"
      - name: DB_DATABASE
        value: "odc"
      - name: DB_USERNAME
        valueFrom:
          secretKeyRef:
            name: odcread-secret
            key: username
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: odcread-secret
            key: password

    # Resource limits
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
