apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-workflows
spec:
  releaseName: argo-workflows
  chart:
    spec:
      chart: argo-workflows
      version: "0.40.14"
      sourceRef:
        kind: HelmRepository
        name: argo-repository
  interval: 5m
  values:
    singleNamespace: true
    server:
      # Allow UI to retrieve objects from AWS S3 bucker
      serviceAccount:
        create: true
        name: "argo-workflows-server"
        annotations:
          eks.amazonaws.com/role-arn: "arn:aws:iam::236122835646:role/iam-role-for-argo-workflow-service-account"
      # Logging configuration
      logging:
        level: info
        globallevel: "0"
      readinessProbe:
        initialDelaySeconds: 60
        periodSeconds: 20
        timeoutSeconds: 5
        failureThreshold: 5

    # Workflow Controller
    controller:
      logging:
        level: info
        globallevel: "0"
      workflowNamespaces:
        - argo-workflows

    # Workflow configuration
    workflow:
      serviceAccount:
        create: true
        name: "argo-workflows-executor"
        namespace: argo-workflows
        annotations:
          workflows.argoproj.io/rbac-rule: "true"
          workflows.argoproj.io/rbac-rule-precedence: "1"
          eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/ArgoWorkflowsExecutorRole" # Replace with actual role ARN
      rbac:
        create: true

    # Artifact repository configuration : replace with real S3 bucket info
    artifactRepository:
      s3:
        bucket: "argo-artifacts-dep"
        region: ap-southeast-3
        keyFormat: "artifacts/{{workflow.namespace}}/{{workflow.name}}/{{pod.name}}"
        useSDKCreds: false

    # Executor configuration
    executor:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
