apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-user-login
  annotations:
    workflows.argoproj.io/rbac-rule: "true"
    workflows.argoproj.io/rbac-rule-precedence: "0"
  labels:
    app.kubernetes.io/name: argo-workflows
    app.kubernetes.io/component: rbac
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-admin-login
  annotations:
    workflows.argoproj.io/rbac-rule: "'argo-admin' in groups"
    workflows.argoproj.io/rbac-rule-precedence: "100"
  labels:
    app.kubernetes.io/name: argo-workflows
    app.kubernetes.io/component: rbac
