apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-user-login
  namespace: argo-workflows
  annotations:
    workflows.argoproj.io/rbac-rule: "true"
    workflows.argoproj.io/rbac-rule-precedence: "0"
  labels:
    app.kubernetes.io/name: argo-workflows
    app.kubernetes.io/component: rbac
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-admin-login
  namespace: argo-workflows
  annotations:
    workflows.argoproj.io/rbac-rule: "'admin' in groups"
    workflows.argoproj.io/rbac-rule-precedence: "100"
  labels:
    app.kubernetes.io/name: argo-workflows
    app.kubernetes.io/component: rbac
---
# Secret for argo-user-login service account
apiVersion: v1
kind: Secret
metadata:
  name: argo-user-login.service-account-token
  namespace: argo-workflows
  annotations:
    kubernetes.io/service-account.name: argo-user-login
type: kubernetes.io/service-account-token
---
# Secret for argo-admin-login service account
apiVersion: v1
kind: Secret
metadata:
  name: argo-admin-login.service-account-token
  namespace: argo-workflows
  annotations:
    kubernetes.io/service-account.name: argo-admin-login
type: kubernetes.io/service-account-token
