apiVersion: v1
kind: ConfigMap
metadata:
  name: postgis-config
  namespace: default
data:
  POSTGRES_DB: datacube
  POSTGRES_USER: datacube
  POSTGRES_PASSWORD: datacube
  # PostGIS specific settings
  POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
