apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

namespace: default
labels:
  - includeSelectors: true
    pairs:
      app: postgis
      component: database
      managed-by: flux
