---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: terria
  namespace: terria
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: terria
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: terria
  namespace: terria
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: terria
